### ISSUE TITLE
about multi gpu processing 

### ISSUE THREAD

**Issue by amiltonwong** [dvlab-research/Stratified-Transformer#2] opened 2022-03-30 02:23 UTC
Hi, authors,

Thanks a lot for releasing the code. Does the current package only support multi-gpu processing (as it's found that SyncBN is used)? How could I run the training code if only a single GPU is allowed?

Thanks~

**Comment by X-Lai** [comment] 2022-03-30 03:04
You can change the `train_gpu` to `[0]`, and modify `batch_size` and `batch_size_val` accordingly. But I am not sure whether it will impair the performance.

**Comment by aoligei178** [comment] 2022-03-30 08:28
Hi, authors,
Thanks a lot for your awesome work. I want to know how much time it costs to reproduce your performance by 2 RTX3090?
What GPU did you use? 
May I ask for your training log?

**Comment by aoligei178** [comment] 2022-03-30 08:28
Hi, authors,
Thanks a lot for your awesome work. I want to know how much time does it cost to reproduce your performance by 2 RTX3090?
What GPU did you use?
May I ask for your training log?

**Comment by X-Lai** [comment] 2022-03-30 08:53
Thanks for your interest in our work. 

We use 4 RTX2080Ti for training. Training on S3DIS consumes about 70 hours for 100 epochs with 30 data loops, and on ScanNetv2 it consumes about 100 hours for 100 epochs with 6 data loops. Actually, training for 50 epochs is enough for both datasets (the gap with 100 epochs is only about 1.0% mIoU). 

The training logs have been released in the README.md file. Note that the released training logs are based on our original CUDA implementation, which is much slower than current implementation in our repo (since we have optimized the CUDA implementation with shared memory).

**Closed** 2022-04-01 05:10 UTC
